# Generated by Django 5.2.3 on 2026-04-30 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_sheets', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SheetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ocr/sheets/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('review_required', 'Review required'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('raw_ocr_response', models.JSONField(blank=True, null=True)),
                ('final_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('quota_deducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveSmallIntegerField()),
                ('group_number', models.PositiveSmallIntegerField()),
                ('field_type', models.CharField(choices=[('N', 'N'), ('F', 'F'), ('S', 'S')], max_length=1)),
                ('extracted_value', models.CharField(blank=True, default='', max_length=32)),
                ('confidence', models.FloatField(default=0)),
                ('corrected_value', models.CharField(blank=True, default='', max_length=32)),
                ('is_low_confidence', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='ocr.sheetupload')),
            ],
            options={
                'ordering': ['row_number', 'group_number', 'field_type'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'row_number', 'group_number', 'field_type'), name='unique_sheet_grid_cell')],
            },
        ),
    ]
