# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedcell",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
